### ISSUE TITLE
Not Scrolling in LoginActivity

### ISSUE THREAD

**Issue by jainkuniya** [the-dagger/lEarnit#7]
In landscape mode, it is not scrolling.
Improvement: Make ScrollView as parent in activity_login.xml.
Should I do it?
![device-2016-11-01-110551](https://cloud.githubusercontent.com/assets/18511177/19880449/4c1d1404-a023-11e6-99e6-eabf2d38b65c.png)

**Comment by the-dagger** [comment]
Sure, please go ahead. 👍

**Comment by jainkuniya** [comment]
@the-dagger created PR #8. Please review it.

**Comment by jainkuniya** [comment]
@the-dagger  thanks
